name: finbif-observation-trends-r-tool
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - jupyterlab
  - r-base=4.3
  - r-irkernel
  - r-remotes
  - r-dplyr
  - r-ggplot2
  - r-lubridate
  - r-leaflet
  - r-sf
  - r-ggspatial
